# Generated by Django 6.0.4 on 2026-04-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='quantidade',
        ),
    ]
